[tox]
env_list = unit
requires = tox-uv

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests

[testenv:unit]
description = Run unit tests
runner = uv-venv-lock-runner
dependency_groups = dev
pass_env =
    PYTHONPATH
commands =
    pytest \
        -v \
        --tb=short \
        {posargs}

[testenv:integration]
description = Run integration tests (requires Juju, a K8s controller, and built artifacts)
runner = uv-venv-lock-runner
dependency_groups = integration
pass_env =
    CHARM_PATH
    OCI_IMAGE
    JUJU_CONTROLLER
    JUJU_MODEL
set_env =
    PYTHONPATH = {tox_root}/src
commands =
    pytest \
        -v \
        -s \
        --tb=native \
        --log-cli-level=INFO \
        {[vars]tests_path}/integration \
        {posargs}
